baseURL = "httpa://mojtab23.github.io/"
languageCode = "en-us"
title = "Mojtaba Zarezadeh - Personal Website"
theme = "LoveIt"

[params]
# LoveIt theme version
version = "0.2.X"
# site description
description = "Mojtaba Zarezadeh's personal website."
# site keywords
keywords = ["Mojtaba", "Mojtaba Zarezadeh", "Personal", "Blog", "Developer"]
images = ["images/mojtaba_zarezadeh.jpg"]
[menu]
[[menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Posts"
url = "/posts/"
# title will be shown when you hover on this menu link
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 2
[[menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 3

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
